AllCops:
  Exclude:
    - 'test/fixture/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/PercentLiteralDelimiters:
  Enabled: false