language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-9

script:
  - cd test/fixture/rspec_2_rails_3_2 && BUNDLE_GEMFILE=Gemfile bundle install && BUNDLE_GEMFILE=Gemfile bundle exec test_diff build_coverage spec spec/spec_helper.rb
  - bundle exec rake