source 'https://rubygems.org'

gem 'rails', '~> 3.2.0'
gem 'rake', '~> 10.0'
gem 'sqlite3'

group :test, :development do
  gem 'test-unit'
  gem 'rspec-rails', '~> 2.6.0'
  gem 'test_diff', path: '../../../'
end
