#!/usr/bin/env ruby
require 'rubygems'
require 'thor'

require 'test_diff'

# thor class to allow execution
class TestDiffBuilder < Thor
  desc 'build_coverage spec', 'runs the specs and generates reverse_coverage'
  def build_coverage(spec_folder = 'spec', pre_load = nil, continue = nil)
    TestDiff::BuildCoverage.new(spec_folder, pre_load, continue).run
    track_build
  end

  desc 'track build', 'track this HEAD as the last test diff index'
  def track_build(git_dir = nil, sha1 = nil)
    TestDiff::TrackBuild.new(sha1, git_dir).run
  end

  desc 'rspec', 'runs the specs difference between the branches'
  def rspec(spec_folder = 'spec', groups_of = nil, group = '0')
    TestDiff::RunDiff.new(spec_folder, groups_of, group).run
  end

  desc 'build_coverage_diff spec', 'runs the specs difference between the branches'
  def build_coverage_diff(spec_folder = 'spec', pre_load = nil, continue = nil)
    TestDiff::BuildCoverageDiff.new(spec_folder, pre_load, continue).run
    track_build
  end
end

TestDiffBuilder.start(ARGV)
